# Form implementation generated from reading ui file 'bioReg_2.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import logo_rc

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(598, 314)
        self.logo = QtWidgets.QLabel(Form)
        self.logo.setGeometry(QtCore.QRect(10, 20, 161, 61))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/NewPrefix/ЛОГО НГУЭУ_без текста.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.RegWindow = QtWidgets.QLabel(Form)
        self.RegWindow.setGeometry(QtCore.QRect(180, 10, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.RegWindow.setFont(font)
        self.RegWindow.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.RegWindow.setObjectName("RegWindow")
        self.label_reg = QtWidgets.QLabel(Form)
        self.label_reg.setGeometry(QtCore.QRect(60, 110, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_reg.setFont(font)
        self.label_reg.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_reg.setObjectName("label_reg")
        self.regRegButton = QtWidgets.QPushButton(Form)
        self.regRegButton.setGeometry(QtCore.QRect(150, 220, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.regRegButton.setFont(font)
        self.regRegButton.setObjectName("regRegButton")
        self.regBackButton = QtWidgets.QPushButton(Form)
        self.regBackButton.setGeometry(QtCore.QRect(320, 220, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.regBackButton.setFont(font)
        self.regBackButton.setMouseTracking(False)
        self.regBackButton.setObjectName("regBackButton")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(60, 130, 228, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.RegWindow.setText(_translate("Form", "Регистрация студента"))
        self.label_reg.setText(_translate("Form", "Введите личный номер студента"))
        self.regRegButton.setText(_translate("Form", "Зарегистрировать"))
        self.regBackButton.setText(_translate("Form", "Назад"))
   


if __name__ == "__main__":
    import sys
    
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
