# Form implementation generated from reading ui file 'bioSystemMain.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import logo_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 346)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(10, 20, 161, 61))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/NewPrefix/ЛОГО НГУЭУ_без текста.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.logoText = QtWidgets.QLabel(self.centralwidget)
        self.logoText.setGeometry(QtCore.QRect(180, 10, 481, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.logoText.setFont(font)
        self.logoText.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.logoText.setObjectName("logoText")
        self.regButton = QtWidgets.QPushButton(self.centralwidget)
        self.regButton.setGeometry(QtCore.QRect(220, 110, 261, 61))
        self.regButton.setObjectName("regButton")
        self.IdentButton = QtWidgets.QPushButton(self.centralwidget)
        self.IdentButton.setGeometry(QtCore.QRect(220, 190, 261, 61))
        self.IdentButton.setObjectName("IdentButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Биометрическая система НГУЭУ"))
        self.logoText.setText(_translate("MainWindow", "Биометрическая система НГУЭУ"))
        self.regButton.setText(_translate("MainWindow", "Зарегистрировать студента"))
        self.IdentButton.setText(_translate("MainWindow", "Идентифицировать студента"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
